### ISSUE TITLE
인스타 API 영문이외 한글, 일본어 등 검색시 에러

### ISSUE THREAD

**Issue by namkim** [namkim/instag#15]
## 인스타 API 영문이외 한글, 일본어 등 검색시 에러

이하insert_tag_img_api.py** 바치 검색어 한글, 일본어의 경우 에러
```
tag_search, next_tag = api.tag_search(u'검색어')
```
로컬에서만 발생되는지 검증 필요

```
<type 'str'>
Traceback (most recent call last):
  File "./manage.py", line 37, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/free31/git/instag/src/common/management/commands/insert_tag_img_api_new.py", line 29, in handle
    tag_recent_media, next = unauthenticated_api.tag_recent_media(tag_name=u'사랑')
  File "/Users/free31/git/instag/src/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/Users/free31/git/instag/src/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/Users/free31/git/instag/src/instagram/bind.py", line 137, in _do_api_request
    raise InstagramAPIError(content_obj.get('code'), content_obj.get('error_type'), content_obj.get('error_message'))
instagram.bind.InstagramAPIError: (403) OAuthForbiddenException-Invalid signed-request: Signature does not match

```

**Comment by namkim** [comment]
참조
http://python.g.hatena.ne.jp/mhrs/20060609/p1

**Comment by namkim** [comment]
일본어 한국어로 사진 검색이 안됨

tag 검색 가능
```
tag_search, next_tag = api.tag_search('검색어')
```

이미지 검색 에러
```
tag_recent_media, next = api.tag_recent_media(tag_name='검색어')
```

**Comment by namkim** [comment]
인스타그램에서 제공하는 현재 인기이미지를 취득하도록 했습니다.
한국쪽 인기이미지만을 취득하는 방법이나 국가별 지역별로 취득이 가능한지 조사해볼 필요가 있음
```
/media/popular
https://api.instagram.com/v1/media/popular?access_token=ACCESS-TOKEN
```

**Comment by namkim** [comment]
문제는 해결하였습니다.
python-instagram의 모듈쪽을 일단 수정해서 사용하도록 하였습니다. 인코딩 문제였습니다.
src/instagram/bind.py
```
# value = quote(self.parameters[name])
value = self.parameters[name].encode('utf8')
```
