### ISSUE TITLE
바치 에러남

### ISSUE THREAD

**Issue by kimnam31** [namkim/instag#2]
바치 에러 수정

**Comment by namkim** [comment]
以下のバッチを実行するとエラーになる
```
python ./manage.py insert_tag_img_api
```

```
Traceback (most recent call last):
  File "./manage.py", line 37, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/free31/.virtualenvs/wemake/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/free31/git/instag/src/common/management/commands/insert_tag_img_api.py", line 19, in handle
    tag_recent_media, next = api.tag_recent_media(tag_name=tag_search[0].name)
  File "/Users/free31/git/instag/src/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/Users/free31/git/instag/src/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/Users/free31/git/instag/src/instagram/bind.py", line 137, in _do_api_request
    raise InstagramAPIError(content_obj.get('code'), content_obj.get('error_type'), content_obj.get('error_message'))
instagram.bind.InstagramAPIError: (403) OAuthForbiddenException-Invalid signed-request: Signature does not match
```

**Comment by namkim** [comment]
instagramPlayer Null데이터로 루프를 돌려서 에러가..
```
class Command(BaseCommand):
    def handle(self, *args, **options):
        for i in InstagramPlayer.objects.all():
```
